### ISSUE TITLE
Simple greeting

### ISSUE THREAD

**Issue by Daniil-Mudrak** [redexp/GeekHub-2020.js#1]
```javascript
console.log('Hello, Season X!')
```

Look forward to the new season of **GeekHub!**
Good luck in the season X!!!🔥⚛️👨‍💻

**Comment by redexp** [comment]
@Daniel-developer5 тебе лично первый урок - исправь своё сообщение, чтобы оно выглядело с подсведкой синтаксиса js, вот так
```js
console.log('Hello, Season X!')
```
Look forward to the new season of **GeekHub**!
Good luck in the _season X_!!!🔥⚛️👨‍💻

**Comment by Sergey-Markov** [comment]
console.log('Hello, Season X!')

**Comment by Sergey-Markov** [comment]
> console.log('Hello, Season X!')

**Comment by Sergey-Markov** [comment]
> ```js
> console.log('Hello, Season X!')
> ```
