### ISSUE TITLE
Не удается загрузить дз

### ISSUE THREAD

**Issue by o-datsiura** [redexp/GeekHub-2020.js#11]
В WebStorm'e нет опции Git. Как можно по-другому загрузить на репозиторий работу?

**Comment by KonstantinFaleev** [comment]
В WebStorm Git есть. 
Можно еще через Terminal.
git add .
git commit -m "Commit"
git push

**Comment by kvils** [comment]
по git(y) могу  помочь

**Comment by o-datsiura** [comment]
спасибо вам, разобрался
