### ISSUE TITLE
Сертификаты

### ISSUE THREAD

**Issue by redexp** [redexp/GeekHub-2020.js#27]
@YuliiaKavytska @IrshakAnna-Mariia @AndriiVitrenko @BogdanSav @volus1986 @AlexKif @kononyukii @RomanTaran @ANScorp @Daniel-developer5 

Всех поздравляю, все справились с заданием! Кто-то лучше, кто-то хуже, но это нормально. Я очень доволен результатом курсов - 10 сертификатов - это супер результат, даже не смотря на то что в начале вас было 140. У меня из головы не выходит аналогия со старатилями во время золотой лихорадки, когда они просеивали тонны земли в поиске крупиц золота.  Ну вы поняли кто здесь кто в этой аналогии.. 
```
кстати из интересного, прочитал про золотую лихорадку в Клондайке, то у них была похожая ситуация с нами
около 1 миллиона человек вознамерились отправиться за золотом в Клондайк;
около 100 тысяч действительно за ним пошли;
около 60 тысяч человек погибли по дороге, либо вернулись назад;
около 40 тысяч человек дошло до Доусона;
только 4 тысячи из них действительно нашли золото.
т.е. только 0.4 %, от всех желающих, добились результата. В нашем случае это 7%
```
Я в этом issue буду держать вас в курсе как и когда вы сможете получить свои сертификаты. А пока я выкладываю текста всех выпускных, которые я придумывал для вас. Вы можете попрактиковаться ещё разок другой, прежде чем отправлять заявку на трудоустройство куда-либо.

**Comment by redexp** [comment]
Приложение "Контакты" - повторяем полностью функционал контактной книжки в телефоне

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должен сохраняться свой список контактов. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина показываем список контактов в формате: аватарка, имя, телефон и две кнопки - "позвонить" и "редактировать". "Позвонить" - должна быть ссылкой с адресом `tel:+380631112233`. "Редактировать" - переходит на форму редактирования контакта. 

На форме должны быть поля редактирования: имя (обязательное больше 3 букв), телефон (обязательно, валидировать два формата +380xxxxxxxxx или 0xxxxxxxxx), имейл (необязательно), домашний адрес (необязательно) и коментарий (необязательно). Телефонов может быть несколько - добавляем с помощью кнопок "плюс" и "минус". Перед телефонным номером должна быть иконка оператора (лайф или киевстар, можно больше по желанию) которая определяется сразу во время ввода номера. Должна быть возможность загрузить новую аватарку. Я, кажется, не рассказывал как это сделать, [вот как это делается в браузере](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0_%D1%84%D0%B0%D0%B9%D0%BB%D0%B0_%D0%BD%D0%B0_%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80), а для того чтобы принять на ноде, то самое простое решение [multer](https://www.npmjs.com/package/multer).

Под формой три кнопки: отменить, удалить, сохранить.

**Comment by redexp** [comment]
Приложение "События" - список событий по датам

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должен сохраняться свой список событий. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина переходим на страницу, на которой выводим таблицу, которая представляет текущий месяц по дням, вот так

### ◀️ Апрель ▶️

Пн|Вт|Ср|Чт|Пт|Сб|Вс
--|--|--|--|--|--|--
  |  |  | 1| 2 (**3**)| 3| 4| 5
 6| 7| 8 (**1**)| 9|10|11|12

в скобках выводит количество событий в этот день. Должно быть две кнопки для перехода на предыдущий и следующий месяц. При клике на день выводим список событий

На списке событий выводим время каждого события и описание события. События можно добавлять, удалять, редактировать. Время можно указывать как инпуте с валидацией, типа `xx:xx`, так и двумя полями, для часов и минут, так и использовать сторонний компонент. 

Для работы с датами советую посмотреть на [moment](https://www.npmjs.com/package/moment)

**Comment by redexp** [comment]
Приложение "Еженедельник" - список событий рабитых по неелям

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должен сохраняться свой список событий. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина переходим на страницу, на которой выводим таблицу, которая представляет текущую неделю по дням, вот так
### ◀️ 22 - 28 Марта ▶️

__|Пн|Вт|Ср|Чт|Пт|Сб|Вс
--|--|--|--|--|--|--|--
00:00|  |  |  |  |  |  |  
00:15|  |  |  |  |  |  |  
00:30|  |  |  |  |  |  |  
01:00|  |  |  |  |  |  |  
....|  |  |  |  |  |  |  
23:45|  |  |  |  |  |  |  

Должно быть две кнопки для перехода на предыдущую и следующую неделю. При клике на ячейку (например Вт/08:15) выводим форму добавления события

В форме можем ввести описание события и указать цвет (которым будут зарисовываться ячейки в таблице). Время начала события сразу введено (08:15) и конец события будет + 30 мин, т.е. 08:45, которое можно поменять. Время можно указывать как инпуте с валидацией, типа `xx:xx`, так и двумя полями, для часов и минут, так и использовать сторонний компонент. Внизу формы должны быть три кнопки: отмена, удалить, сохранить.

После сохранения событие заполняет соответсвующие ячейки и содержит в себе описание, бэкграунд в соответсвующем цвете. Текст может быть большой, заполняющий больше одной ячейки, но он не дольше растягивать событие.

Событие можно растягивать вниз, можно полностью перетягивать, что меняет время начала и конца события, автоматически сохраняя его на сервер.

**Comment by redexp** [comment]
Приложение "Чат"

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должены сохраняться свои чаты. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина, пользователь видим список других зарегистрированных пользователей (кроме себя естественно). Напротив каждого пользователя видно сколько сообщений было в переписке с этим пользователем. При клике на пользователя - открывается чат.

В чате есть инпут для ввода сообщения. При нажатии на энтер - сообщение отправляется в чат. Другой пользователь, если он тоже в чате, моментально видит новое сообщение. Сообщения текущего пользователя показываются справа, а оппонента - слева, как в вайбере или фб месенджере. Над каждым сообщением видно время отправки в формате `8:15`

Если пользователь не был в чате когда ему отправили сообщение, то количество пропущеных сообщений показывается в скобках и жирным справа от общенго количества сообщений в списке зарегистрированных пользователей.

Если успеешь, дополнительно можно добавить отправку картинок в чат.

**Comment by redexp** [comment]
Прграмма "Файловый менеджер" - выводит список папок и файлов

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должен сохраняться свой список файлов. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина пользователю показывает его папки и файлы (в начале будет пусто). Пользователь может добавить новую папку или загрузить новый файл. Я, кажется, не рассказывал как это сделать, [вот как это делается в браузере](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0_%D1%84%D0%B0%D0%B9%D0%BB%D0%B0_%D0%BD%D0%B0_%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80), а для того чтобы принять на ноде, то самое простое решение [multer](https://www.npmjs.com/package/multer). 

После добавления папки - она отображается в списке с иконкой папки. В папку можно войти двойным кликом, после чего показывается содержимое этой папки - другие папки и файлы. Перед каждым файлом должна быть отдельная иконка которая показывает - это документ (pdf, doc, docx) или картинка (png, jpg) или аудио (mp3, wav) или неизвестный файл. После имени файла должно показывать его размер в читаемом виде типа `50 Kb` или `45.3 Mb`. 

При двойном клике на файл - он скачивается. При наведении курсора на файл картинку - показывается превью этой картинки.

При правом клике - показываем контекстное меню с пунктами: копировать, вырезать, удалить, переименовать. Если мы что-то скопировали или вырезали, то при правом клике на свободном месте должно появится контекстное меню с пунктом "вставить"

**Comment by redexp** [comment]
Приложение "Галерея" - хранилище фотографий

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должен сохраняться свои фотографии. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина, пользователь попадает на список фотографий (вначале он будет пустым). Пользователь может добавить новую фотографию. Я, кажется, не рассказывал как загружать файлы, [вот как это делается в браузере](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch#%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0_%D1%84%D0%B0%D0%B9%D0%BB%D0%B0_%D0%BD%D0%B0_%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80), а для того чтобы принять на ноде, то самое простое решение [multer](https://www.npmjs.com/package/multer). После загрузки картинка тутже появляется в списке с превью. 

Справа от фото должно показывать дату загрузки и размер фото в читаемом формате типа `10 Kb` или `12.5 Mb`. Ещё правее - кнопка "удалить".
Слева от фотографии должен быть чекбокс, как только один из них зачекали, то появляется кнопка "Создать альбом". Т.е. пользователь выделяет нужное количество фото и объединяет их в альбом. При создании альбома - необходимо указать его название.

После создания альбома - фотографии пропадают из общего списка, в самом начале списка появляется новый пункт с именем альбома и количеством фото в нём. Справа от количества - кнопка "удалить альбом", при клике должно предлагать два варианта: "Удалить вместе с фотографиями" или "Перенести фотографии в общий список". При клике на альбом появляется слайдшоу с фото в виде - снизу маленькими первью все фото расположенные по горизонтали, а на весь экран над ними первое фото из списка с двумя стрелками по бокам "предыдущее фото" и "следующее фото". Текущее фото должно выделятся в нижнем горизонтальном списке.

**Comment by redexp** [comment]
Приложение "Домашняя бухгалтерия"

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должена сохраняться своя бухгалтерия. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина показывается список на что были потрачены деньги по времени. Типа такого

Дата | Тип | Сумма | Коментарий
-----|-----|-------|-----------
8 марта 8:15 | Разное | 700 | цветы
вчера 20:45 | Магазин | 120.5 | 
сегодня 9:00 | Кофе | 45 | 

Под списком инпут, в который нужно вводить новый пункт. Формат ввода может быть произвольный, например `бенз 600` что должно распознаться как `сегодня 10:00, Заправка бензином, 600` или `пт 20.00 маг 145` - `пт` значит "в прошлую пятницу", `20.00` значит "в 20:00", `маг` - тип "Магазин" и `145` - сумма. Каждую запись можно удалить или отредактировать.

Должна быть кнопка для добавления сокращений для даты типа

Дата | Сокращение
-----|-----------
сегодня | с, сег
вчера | вч, вчер
прошлый понедельник | пн, пон
прошлый вторник | вт
.... | 

Должна быть кнопка добавления сокращения для "Типов" трат, где пользователь вводит как тип, так и сокращение

Тип | Сокращение
----|-----------
Магазин | маг
Бензин | бенз
..... | 

Время можно указывать в нескольких форматах `HH.MM`, `HH:MM`, `HH`.

На странице списка растрат можно переключать три вида. 

1. Список потраченых денег
2. Сгруппированный список по типам, в рамках одного месяца, где выводится сумма потраченых денег на каждый тип и разница между предыдущим месяцем, вот так

Тип | Сумма | Разница
----|-------|--------
Магазин | 7423 | +505
Бензин | 1200 | -100
... | | 

`+` значит что в этом месяце потратил больше, `-` соответственно - меньше. Если без разницы то выводить `0`

И третий вид - сгрупированные все растраты по месяцам

Месяц | Сумма | Разница
-------|-------|--------
Январь | 17423 | +505
Февраль | 17100 | -323
... | |

**Comment by redexp** [comment]
Приложение "Генеалогическое древо" - конструктор генеалогического древа

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. За каждым пользователем должено сохраняться своё дерево. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина видим дерево (в начале только один блок представляющи текущего пользователя). В каждом блоке сверху две кнопки: "Мама" и "Папа", нажимая на которые выше добавляется соответствующий блок с инпутом для ввода имени. Внизу блока ещё две кнопки "Сын" и "Дочь", которая добавляет ниже текущего блока новый блок с инпутом для ввода имени. Справа от блока должна быть кнопка "Муж" или "Жена" в зависимости от пола текущего блока, которая добавляет блок справа. Мужей и жён может быть несколько (развелись, снова женились), от кого какие дети можно не показывать.

По любому действию с деревом происходит автоматическое сохранение на сервер, по этому кнопки Сохранить не должно быть.

Генеалогическое дерево по факту сложнее чем то что описано выше - могут быть однополые браки, усыновлённые дети, в текущем задании мы это не учитываем.

**Comment by redexp** [comment]
Игра "Балда"

При входе требует логин - форма с двумя полями для имейла и пароля. Кнопка для возможности зарегистировать нового пользователя. Все данные хранятся на сервере. Пароли хранить с помощью [bcrypt](https://www.npmjs.com/package/bcrypt) (прочитай, первые две ссылки в описании, чтобы понять суть bcrypt)

После логина выводим список пользователей которые сейчас онлайн, по которым можно кликнуть и начать игру.

После клика по пользователю показываем поле 5х5 посреди которого написано "БАЛДА". Суть игры, я надеюсь объяснять детально не нужно. Каждый ходит по очереди, добавляет на свободную ячейку букву, после чего прокликивает по буквам которые должны составить слово и нажимает на кнопку "Проверить". Слово проверяем через википдию, это можно сделать одной из этих библиотек [Wiki API for JS](https://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:API#JavaScript). Если в вики есть статься про это слово, то оно засчитывается - добавляется в табличку типа 

Сергей | - | Андрей | -
-------|-----|--------|-----
КАРАНДАШ | 8 | КАРМАН | 6
.... |   |   |   
**сумма** | 68 |   | 54

Игра заканчивается когда выбрано правильное слово и на поле нету больше пустых ячеек

**Comment by redexp** [comment]
```
26 травня (середа), 18:30 кінець сезону. Попередньо: кінотеатр “Україна“, велика зала. 
Запрошуємо випускників, а також їх рідних, які хотіли б їх привітати. Розсадка з дистанцією
```
Создайте у себя issue `Контакты` где напишите: 
1. Хотите ли вы вообще получать сертификат
2. Полное имя українською
3. Хотите ли вы чтобы ваши контакты попали к рекрутерам IT компаний Черкасс
4. Контакты через которые вы хотелибы чтобы с вами связались

**Comment by redexp** [comment]
Всем кому нужны сертификаты - попросили написать своё имя латиницей... допишите в issue с контактами в формате сначала фамилия потом имя

**Comment by redexp** [comment]
Так же сказали, что почему-то важно дать имейл - допишите коментарием, в issue с контактами, свой имейл

**Comment by redexp** [comment]
всем пришёл имейл где будут вручать сертификаты?

**Comment by RomanTaran** [comment]
@redexp Да, сегодня в 18:00 в кинотеатре "Украина"

**Comment by andrewvitrenko** [comment]
@redexp да

**Comment by redexp** [comment]
ставим лайк под вопросом, не нужно писать "да" каждому

**Comment by BogdanSav** [comment]
> всем пришёл имейл где будут вручать сертификаты?

це те що від вас чи ще якесь є?

**Comment by alexkif** [comment]
Мне не пришел

ср, 26 трав. 2021 о 15:08 Sergii Kliuchnyk ***@***.***> пише:

**Comment by redexp** [comment]
тут задали интересный вопрос - сколько просить первую ЗП, отвечаю

для старта 300 - 400 $, но обязательно с частым пересмотром зарплаты. Так и спрашивайте "Как часто у вас пересматривается зарплата" - как правило отвечают "Раз в год иногда раз в пол года", а вы апелируйте "Я думаю, я смогу проявить себя быстрее чем через пол года. Можно будет пересмотреть мою ЗП через три месяца?". Но это ставка. Если вам 300-400 очевидно мало для жизни, то вы жопу будете рвать, но через три месяца покажете крутой результат. А если 300-400 вам ок, то лучше не рыпаться и остановиться на пересмотре ЗП через пол года.

Не стесняйтесь дёргать через договоренное время рекрутера с которым договаривались, о том что пришло время, и вы действительно видете прогресс на лицо. Не каждый рекрутер добросовестно записывает себе в календарь событие о том что с вами нужно будет пересмотреть ЗП. Если вас мурыжат и достаточно долго оттягивают этот разговор, то смело задумывайтесь о переходе в более добросовестную компанию, в которой со старта уже просите 400-600, так как у вас уже будут агрументы, вы уже не джуник с нулевым опытом, вы уже джуник с опытом работы в компании, в команде, вы лучше понимаете какого рода задачи вы выполняете легко, какие тяжело, вы понимаете что вам нужно подтянуть и т.п.

Не сильно наглейте, но и не ссыте. Если вы на работе жопу рвёте, то вашу порваную жопу заметят, а если ваша жопа цела, как и у всех остальных, то вас и не заметят )))

**Comment by redexp** [comment]
@YuliiaKavytska  @Daniel-developer5 @kononyukii @AlexKif четыре сертификата у меня, завтра в 13:20 в Сантимо подойти сможете?

**Comment by Daniil-Mudrak** [comment]
@redexp а можна після 18? Чи, коли вам зручно в інший час?

**Comment by alexkif** [comment]
Я смогу если что

пн, 7 черв. 2021 о 19:29 Sergii Kliuchnyk ***@***.***> пише:

**Comment by alexkif** [comment]
Так сегодня подходить в 13:20?

пн, 7 черв. 2021 о 19:29 Sergii Kliuchnyk ***@***.***> пише:

**Comment by Daniil-Mudrak** [comment]
@redexp Так коли можна підійти за сертифікатами?
