### ISSUE TITLE
Загальний чат для учасників

### ISSUE THREAD

**Issue by alexmay112** [redexp/GeekHub-2020.js#7]
всім привіт, посилання на загальний чат в слаку https://join.slack.com/t/gh2020-workspace/shared_invite/zt-iopkm0i9-ggydEnqBqr5aerbUaHLKfQ

якщо хтось має бажання, то можна організувати чат в телеграмі, але тут можна створювати гілки відповідей.
всі бажаючі - долучайтесь. хто знає/вміє як зробити чат в слаку кращим і організованішим - робіть) бо я мало що тут розумію.

чат не для того, щоб тривожити викладача 24/7, він - для учасників, для всіх, кому потрібна допомога, або хто радо її надасть комусь за щире дякую)

**Comment by andrewvoinarovskyi** [comment]
https://t.me/joinchat/GQZMIRNeiIYwpU8R4HJx-w
чат в телеграм

**Comment by redexp** [comment]
Предупреждаю, не стремитесь найти быстрые ответы "как сделать домашку". Если вы просто скопируете чужую домашку, то ничему не научитесь.

**Comment by MykYarovenko36** [comment]
Здравствуйте. Меня бот посылает на все четыре стороны, ему не нравится значение поля #result, не могу понять причины его волнения. Как быть?

**Comment by zzzfisherzzz** [comment]
Есть баги у бота который проверяет задание? Потому что я запушил, ввожу условие a1 > b1 и когда 'true' в result меняется background на тот, который нужно.  Но когда проверил бот, то пришло такое сообщение: "Неправильное значение в поле #result после ввода чисел и формулы".

**Comment by Arsen4453** [comment]
Добрый вечер, я создал новый репо и запушил в него домашку, нотификейшн(форму) заполнил и отправил ещё днём, я успею попасть под проверку ?)

**Comment by redexp** [comment]
завтра утром бот проверяет последний раз

**Comment by Arsen4453** [comment]
Ну это круто, я как раз запушил дз, мне очень интересно я правильно всё сделал или допустил ошибку


30 жовтня 2020, 21:35:13, від "Sergii Kliuchnyk" < notifications@github.com >:



завтра утром бот проверяет последний раз

**Comment by Arsen4453** [comment]
Извините, возможно сейчас мне имеет смысл запереживаться, хотелось бы узнать вам пришло что то вроде нотификейшена что я вас добавил в свой приватный репо или нет ?)

**Comment by MykYarovenko36** [comment]
Добрый день. 
Получил сегодня от бота ответ - 
Неправильный background-color (#F9D0C4) поля input[name="full_name"]. После ввода **_правильного украинского имени_** должно быть #C2E0C6
 Я не понял **сути** условия поставленной задачи. Поле ввода должно выполнять проверку на правильное украинское имя или "хоть-бы-шо" просто украинскими буквами без учёта регистра и наличия отступов между слов. 
Подскажите пожалуйста.
