### ISSUE TITLE
Зразу не міняє колір #result

### ISSUE THREAD

**Issue by VadymBezsmertnyi** [redexp/GeekHub-2020.js#8]
Все зробив але коли ввожу умову (наприклад a1<b1), колір воно зразу не міняє а тільки після того як я щось змінюю інше. Як це виправити, щоб міняло зразу після вводу умови міняло колір?

**Comment by Alexandr-Kravchenko** [comment]
додай до свою функцію test
document.querySelectorAll('input[name],` #formula').forEach(function (input) ...
щоб вийшло
document.querySelectorAll('input[name],` #formula', 'test').forEach(function (input)

**Comment by Alexandr-Kravchenko** [comment]
document.querySelectorAll('input[name],` #formula').forEach(function (input)

**Comment by Alexandr-Kravchenko** [comment]
додай до document.querySelectorAll('input[name],` #formula').forEach(function (input) 
#condition
щоб вийшло
document.querySelectorAll('input[name], #formula, #condition').forEach(function (input) ...
і тоді, при редагуванні input-a #condition
буде спрацьовувати зміна кольору

**Comment by redexp** [comment]
@VadymBezsmertnyi у тебя есть целая неделя чтобы разобраться
