### ISSUE TITLE
Як зрозуміти чи дз не виконано?

### ISSUE THREAD

**Issue by Alexandr-Kravchenko** [redexp/GeekHub-2020.js#9]
Знаю, що дз робимо до наступного заняття. Але Ви написали, що дз в кінці кожного дня перевірятиметься і якщо виконано вірно, бот відпише в issues про це.
 А чи відпише він, коли дз виконано не правильно, не так як потрібно?

**Comment by redexp** [comment]
Давайте я сделаю что он будет писать в любом случае, либо текст почему не выполнено, либо текст что выполнено. После того как домашка будет выполнена, бот присылать сообщения не будет
